version: '2'


services:
    registry:
        extends:
            service: presence
            file: docker-compose-presence.yml
        command:
            - presence
            - run
            - registry

    test:
        extends:
            service: presence
            file: docker-compose-presence.yml
        command:
            - presence
            - run
            - test
        depends_on:
            - registry
