version: '2'


services:
    broker:
        extends:
            service: presence
            file: docker-compose-presence.yml
        command:
            - presence
            - run
            - broker

    registry:
        extends:
            service: presence
            file: docker-compose-presence.yml
        command:
            - presence
            - run
            - registry

    test:
        extends:
            service: presence
            file: docker-compose-presence.yml
        command:
            - presence
            - run
            - test
